version: "3.9"

services:


web:
build:
context: ./apps/web
dockerfile: Dockerfile
container_name: techradar-web
ports:
- "5173:80"
depends_on:
- spring-api
restart: unless-stopped


spring-api:
build:
context: ./apps/backend
dockerfile: Dockerfile
container_name: techradar-spring-api
ports:
- "8080:8080"
env_file:
- .env
environment:
RAG_SERVICE_URL: http://ai-rag-core:8000
CLUSTERING_SERVICE_URL: http://ml-clustering:8001
REDIS_HOST: redis
POSTGRES_HOST: postgres
depends_on:
postgres:
condition: service_started
redis:
condition: service_started
ai-rag-core:
condition: service_started
ml-clustering:
condition: service_started
restart: unless-stopped


postgres:
image: postgres:16-alpine
container_name: techradar-postgres
ports:
- "5432:5432"
environment:
POSTGRES_DB: techradar
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
volumes:
- postgres_data:/var/lib/postgresql/data
restart: unless-stopped



neo4j:
image: neo4j:5
container_name: techradar-neo4j
ports:
- "7474:7474"
- "7687:7687"
environment:
NEO4J_AUTH: neo4j/password
NEO4J_PLUGINS: '["apoc"]'
NEO4J_dbms_security_procedures_unrestricted: apoc.*
NEO4J_dbms_memory_heap_initial__size: 512m
NEO4J_dbms_memory_heap_max__size: 2g
volumes:
- neo4j_data:/data
- neo4j_logs:/logs
restart: unless-stopped



redis:
image: redis:7-alpine
container_name: techradar-redis
ports:
- "6379:6379"
volumes:
- redis_data:/data
restart: unless-stopped


ai-rag-core:
build:
context: ./services/ai-rag-core
dockerfile: Dockerfile
container_name: techradar-rag
ports:
- "8000:8000"
env_file:
- .env
depends_on:
- neo4j
- postgres
restart: unless-stopped


ml-clustering:
build:
context: ./services/ml-clustering
dockerfile: Dockerfile
container_name: techradar-clustering
ports:
- "8001:8001"
env_file:
- .env
volumes:
- ml_clustering_cache:/tmp/ml-clustering-cache
restart: unless-stopped



mlflow-rag:
image: ghcr.io/mlflow/mlflow:v3.1.0
container_name: techradar-mlflow-rag
ports:
- "5001:5000"
volumes:
- ./services/ai-rag-core:/mlflow-data
command:
- mlflow
- server
- --host
- 0.0.0.0
- --port
- "5000"
- --backend-store-uri
- sqlite:////mlflow-data/mlflow.db
- --default-artifact-root
- /mlflow-data/mlruns
restart: unless-stopped



mlflow-clustering:
image: ghcr.io/mlflow/mlflow:v3.1.0
container_name: techradar-mlflow-clustering
ports:
- "5002:5000"
volumes:
- ./services/ml-clustering:/mlflow-data
command:
- mlflow
- server
- --host
- 0.0.0.0
- --port
- "5000"
- --backend-store-uri
- sqlite:////mlflow-data/mlruns.db
- --default-artifact-root
- /mlflow-data/mlruns
restart: unless-stopped

volumes:
postgres_data:
neo4j_data:
neo4j_logs:
redis_data:
ml_clustering_cache:
