-- Bịt lỗ hổng cùng loại với case "SQL" vs "Sql": raw skill tag (nhà tuyển dụng tự gõ
-- trên ITviec, giữ nguyên case) đi qua TechAliasResolver.resolve() — nếu chưa có dòng
-- alias cho tên đó, resolve() trả nguyên văn chuỗi gốc (giữ case), sinh ra :Technology
-- node trùng lặp khác case so với node đã tồn tại (vd "sql"/"Sql"/"SQL" thành 3 node).
--
-- V21 mới chỉ seed các cặp viết tắt/đồng nghĩa (golang->Go, js->JavaScript...), chưa
-- seed alias "tự tham chiếu" (lower(canonical) -> canonical) cho phần lớn TECH_KEYWORDS
-- trong EntityExtractionService.java — nên bất kỳ tên nào trong danh sách đó, nếu nhà
-- tuyển dụng gõ sai case, đều có thể tái diễn lỗi y hệt SQL. Insert dưới đây bổ sung
-- alias tự tham chiếu cho toàn bộ TECH_KEYWORDS còn thiếu (ON CONFLICT DO NOTHING nên
-- không đụng tới các dòng đồng nghĩa đã cố ý gộp khác canonical, vd 'ml'->'Machine
-- Learning', 'golang'->'Go').
INSERT INTO dp_tech_alias_map (alias_normalized, canonical_name, source) VALUES
    -- Ngôn ngữ
    ('python', 'Python', 'seed'),
    ('java', 'Java', 'seed'),
    ('go', 'Go', 'seed'),
    ('rust', 'Rust', 'seed'),
    ('c++', 'C++', 'seed'),
    ('c#', 'C#', 'seed'),
    ('php', 'PHP', 'seed'),
    ('ruby', 'Ruby', 'seed'),
    ('swift', 'Swift', 'seed'),
    ('kotlin', 'Kotlin', 'seed'),
    ('scala', 'Scala', 'seed'),
    ('dart', 'Dart', 'seed'),
    ('perl', 'Perl', 'seed'),
    ('elixir', 'Elixir', 'seed'),
    ('haskell', 'Haskell', 'seed'),
    -- Frontend
    ('react', 'React', 'seed'),
    ('vue', 'Vue', 'seed'),
    ('angular', 'Angular', 'seed'),
    ('svelte', 'Svelte', 'seed'),
    ('next.js', 'Next.js', 'seed'),
    ('nuxt', 'Nuxt', 'seed'),
    ('jquery', 'jQuery', 'seed'),
    ('tailwind', 'Tailwind', 'seed'),
    ('bootstrap', 'Bootstrap', 'seed'),
    ('webpack', 'Webpack', 'seed'),
    ('vite', 'Vite', 'seed'),
    ('html', 'HTML', 'seed'),
    ('css', 'CSS', 'seed'),
    ('sass', 'Sass', 'seed'),
    -- Backend / framework
    ('spring boot', 'Spring Boot', 'seed'),
    ('spring', 'Spring', 'seed'),
    ('django', 'Django', 'seed'),
    ('flask', 'Flask', 'seed'),
    ('fastapi', 'FastAPI', 'seed'),
    ('node.js', 'Node.js', 'seed'),
    ('express', 'Express', 'seed'),
    ('laravel', 'Laravel', 'seed'),
    ('rails', 'Rails', 'seed'),
    ('.net', '.NET', 'seed'),
    ('asp.net', 'ASP.NET', 'seed'),
    ('nestjs', 'NestJS', 'seed'),
    -- Mobile
    ('flutter', 'Flutter', 'seed'),
    ('react native', 'React Native', 'seed'),
    ('android', 'Android', 'seed'),
    ('ios', 'iOS', 'seed'),
    ('xamarin', 'Xamarin', 'seed'),
    -- Data / AI
    ('ai', 'AI', 'seed'),
    ('nlp', 'NLP', 'seed'),
    ('rpa', 'RPA', 'seed'),
    ('machine learning', 'Machine Learning', 'seed'),
    ('deep learning', 'Deep Learning', 'seed'),
    ('computer vision', 'Computer Vision', 'seed'),
    ('big data', 'Big Data', 'seed'),
    ('data science', 'Data Science', 'seed'),
    ('llm', 'LLM', 'seed'),
    ('gpt', 'GPT', 'seed'),
    ('chatgpt', 'ChatGPT', 'seed'),
    ('gemini', 'Gemini', 'seed'),
    ('claude', 'Claude', 'seed'),
    ('tensorflow', 'TensorFlow', 'seed'),
    ('pytorch', 'PyTorch', 'seed'),
    ('keras', 'Keras', 'seed'),
    ('hadoop', 'Hadoop', 'seed'),
    ('spark', 'Spark', 'seed'),
    ('flink', 'Flink', 'seed'),
    ('airflow', 'Airflow', 'seed'),
    ('dbt', 'dbt', 'seed'),
    ('databricks', 'Databricks', 'seed'),
    ('snowflake', 'Snowflake', 'seed'),
    ('power bi', 'Power BI', 'seed'),
    ('tableau', 'Tableau', 'seed'),
    ('bigquery', 'BigQuery', 'seed'),
    -- Database
    ('sql', 'SQL', 'seed'),
    ('nosql', 'NoSQL', 'seed'),
    ('postgresql', 'PostgreSQL', 'seed'),
    ('mysql', 'MySQL', 'seed'),
    ('mongodb', 'MongoDB', 'seed'),
    ('redis', 'Redis', 'seed'),
    ('neo4j', 'Neo4j', 'seed'),
    ('qdrant', 'Qdrant', 'seed'),
    ('elasticsearch', 'Elasticsearch', 'seed'),
    ('cassandra', 'Cassandra', 'seed'),
    ('sqlite', 'SQLite', 'seed'),
    ('oracle', 'Oracle', 'seed'),
    ('mariadb', 'MariaDB', 'seed'),
    ('graphql', 'GraphQL', 'seed'),
    -- Cloud / DevOps
    ('gcp', 'GCP', 'seed'),
    ('azure', 'Azure', 'seed'),
    ('docker', 'Docker', 'seed'),
    ('kubernetes', 'Kubernetes', 'seed'),
    ('ci/cd', 'CI/CD', 'seed'),
    ('devops', 'DevOps', 'seed'),
    ('terraform', 'Terraform', 'seed'),
    ('ansible', 'Ansible', 'seed'),
    ('jenkins', 'Jenkins', 'seed'),
    ('gitlab', 'GitLab', 'seed'),
    ('github actions', 'GitHub Actions', 'seed'),
    ('prometheus', 'Prometheus', 'seed'),
    ('grafana', 'Grafana', 'seed'),
    -- Messaging / infra
    ('kafka', 'Kafka', 'seed'),
    ('rabbitmq', 'RabbitMQ', 'seed'),
    ('grpc', 'gRPC', 'seed'),
    ('websocket', 'WebSocket', 'seed'),
    -- Bảo mật / công nghệ mới
    ('blockchain', 'Blockchain', 'seed'),
    ('web3', 'Web3', 'seed'),
    ('solidity', 'Solidity', 'seed'),
    ('iot', 'IoT', 'seed'),
    ('ar', 'AR', 'seed'),
    ('vr', 'VR', 'seed'),
    ('cybersecurity', 'Cybersecurity', 'seed'),
    ('5g', '5G', 'seed'),
    ('semiconductor', 'Semiconductor', 'seed')
ON CONFLICT (alias_normalized) DO NOTHING;
